### ISSUE TITLE
Contribute a copy of Dex protection source code

### ISSUE THREAD

**Issue by jdjrjjde** [developer-krushna/MT-Document-Provider-Injector#1]
**Source code**
[code.zip](https://github.com/user-attachments/files/18134063/code.zip)

https://www.yjaq.xyz
![C2](https://github.com/user-attachments/assets/fc03a206-7db3-47ae-b485-7d6c4c2f29e5)
> [!TIP]
>  
<details><summary>Details</summary>
<p>

![c3](https://github.com/user-attachments/assets/4486444c-b576-4c03-93e5-5a143cb10400)

</p>
</details>

https://github.com/luoyesiqiu/dpt-shell
@developer-krushna

**Comment by developer-krushna** [comment]
Hi ..I not understand what you need.. based on my understanding you need Dex encryption project right?? Currently I don't have any projects on it as I lost many of my codes because of destruction of my sdcard where I saved my important project data second,Even I lost my phone where I created many new projects..all lost sad

**Comment by jdjrjjde** [comment]
> Hi ..I not understand what you need.. based on my understanding you need Dex encryption project right?? Currently I don't have any projects on it as I lost many of my codes because of destruction of my sdcard where I saved my important project data second,Even I lost my phone where I created many new projects..all lost sad

I have a source code from this project, can you build the serverless apk file for me? Thank you
[ApkProtector.zip](https://github.com/user-attachments/files/18192122/ApkProtector.zip)

https://www.rustore.ru/catalog/app/com.mcal.dexprotect
![k2](https://github.com/user-attachments/assets/9770d10c-90d9-4df5-9ddb-54b0b37cdb14)
![k1](https://github.com/user-attachments/assets/d50094db-7388-45c3-a4ff-64684ec5def5)

**Comment by developer-krushna** [comment]
Sorry I can't build..I don't have much time+ I don't have a perfect device to build such big projects

**Comment by developer-krushna** [comment]
Sorry I can't build..I don't have much time+ I don't have a perfect device to build such big projects
